name: pre-commit

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pre-commit:
    timeout-minutes: 10
    runs-on: multihost_experimental
    steps:
      - uses: actions/checkout@v4
      - name: Run hello script
        run: |
          echo "hello"
          hostname
          touch hello
          sleep 60
