name: On PR

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  checks: write
  pull-requests: write
  id-token: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/call-pre-commit.yml
    secrets: inherit

  inspect-changes:
    runs-on: ubuntu-latest
    outputs:
      skip-build-and-test: ${{ steps.inspect.outputs.skip-build-and-test }}
      run-pr-tests: ${{ steps.inspect.outputs.run-pr-tests }}
      run-perf-tests: ${{ steps.inspect.outputs.run-perf-tests }}
      only-run-forge-models: ${{ steps.inspect.outputs.only-run-forge-models }}
      run-uplift-model-tests: ${{ steps.inspect.outputs.run-uplift-model-tests }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/inspect-changes
        id: inspect

  build-image:
    needs: [ inspect-changes ]
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    uses: ./.github/workflows/call-build-docker.yml
    secrets: inherit

  build-ttxla-release:
    if: needs.inspect-changes.outputs.skip-build-and-test == 'false'
    uses: ./.github/workflows/call-build.yml
    name: "Build tt-xla release"
    secrets: inherit
    needs: [ inspect-changes, build-image ]
    with:
      docker_image: ${{ needs.build-image.outputs.docker-image }}

  perf-benchmark-llmbox:
    # if: needs.inspect-changes.outputs.skip-build-and-test == 'false' && needs.inspect-changes.outputs.only-run-forge-models != 'true' && vars.RUN_PERF_ON_UPLIFT == 'true'  && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'uplift-mlir')
    needs: [ inspect-changes, build-image, build-ttxla-release ]
    uses: tenstorrent/tt-forge/.github/workflows/perf-benchmark.yml@main
    secrets: inherit
    with:
      project: tt-xla
      run_id: ${{ needs.build-ttxla-release.outputs.artifacts_run_id }}
      run_id_source: tt-xla
      ref: main
      perf_regression_check: true
      test-filter: test_llama_3_1_70b_tp
      runs-on-filter: llmbox
      sh-runner: false


  check-all-green:
    if: always()
    needs:
      - pre-commit
      - build-image
      - build-ttxla-release
      - perf-benchmark-llmbox
    runs-on: Ubuntu-latest
    steps:
    - name: Check if the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: build-image, build-ttxla-release, perf-benchmark-llmbox
        jobs: ${{ toJSON(needs) }}
